# Generated by Django 4.2.7 on 2023-11-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин покупателя')),
                ('item', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара')),
                ('total', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cумма заказа')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Kоличество товара')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время регистрации заказа')),
            ],
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv_files/')),
            ],
        ),
    ]
